shim-version: v0.1.9@sha256:410510c9e8e4c7489dd201fede302dee8455075ca28f4f0abbf84bded943b8f1
cvm-version: 0.1.3
ovmf-version: 0.0.2
cpus: 16
memory: 65536

models:
  - name: "whisper-large-v3-turbo"
    repo: "openai/whisper-large-v3-turbo@41f01f3fe87f28c78e2fbf8b568835947dd65ed9"
    mpk: "dd81839982fa01a289f7b60613055e4e1f789503c25a3535b75d53841f7f5b78_1622474752_55d2c545-4d89-5658-9ffd-ce0b4d07ac36"
vllm-args: --task transcription --max-model-len 448 --max-num-seqs 400 --limit-mm-per-prompt audio=1

shim:
  listen-port: 443
  upstream-port: 8089
  control-plane: https://api.tinfoil.sh
  publish-attestation: false
  tls-challenge: dns

containers:
  - name: "kokoro"
    image: "ghcr.io/tinfoilsh/kokoro-fastapi-gpu:v0.2.4"
    args:
      - "--gpus all"
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-audio-processing:latest"

