cvm-version: 0.0.33
ovmf-version: 0.0.2
cpus: 16
memory: 65536

models:
  - name: "whisper-large-v3-turbo"
    repo: "openai/whisper-large-v3-turbo@41f01f3fe87f28c78e2fbf8b568835947dd65ed9"
    mpk: "dd81839982fa01a289f7b60613055e4e1f789503c25a3535b75d53841f7f5b78_1622474752_55d2c545-4d89-5658-9ffd-ce0b4d07ac36"
vllm-args: --task transcription --max-model-len 448 --max-num-seqs 400 --limit-mm-per-prompt audio=1

shim:
  domains:
    - audio-processing.model.tinfoil.sh
  listen-port: 443
  upstream-port: 8089
  control-plane: https://api.tinfoil.sh
  origins:
    - https://tinfoil.sh
    - https://chat.tinfoil.sh

containers:
  - name: "dia"
    image: "ghcr.io/tinfoilsh/dia-tts-server:sha-d754923"
    args:
      - "-v /mnt/ramdisk/model_cache:/app/model_cache"
      - "-v /mnt/ramdisk/reference_audio:/app/reference_audio"
      - "-v /mnt/ramdisk/outputs:/app/outputs"
      - "-v /mnt/ramdisk/voices:/app/voices"
      - "--env HF_HUB_ENABLE_HF_TRANSFER=1"
      - "--gpus all"
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-audio-processing:latest"
